---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-db
  labels:
    name: catalogue-db
  namespace: sock-shop-hardened
spec:
  replicas: 1
  selector:
    matchLabels:
      name: catalogue-db
  template:
    metadata:
      labels:
        name: catalogue-db
    spec:
      containers:
      - name: catalogue-db
        image: weaveworksdemos/catalogue-db:0.3.0
        env:
          - name: MYSQL_ROOT_PASSWORD_FILE
            value: /etc/secrets/MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE_FILE
            value: /etc/secrets/MYSQL_DATABASE
        volumeMounts:
          - name: db-secrets
            mountPath: /etc/secrets
            readOnly: true
        ports:
        - name: mysql
          containerPort: 3306
      volumes:
        - name: db-secrets
          secret:
            secretName: mysql-credentials
      nodeSelector:
        beta.kubernetes.io/os: linux
