---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: front-end
  namespace: sock-shop-hardened
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carts
  namespace: sock-shop-hardened
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalogue
  namespace: sock-shop-hardened
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders
  namespace: sock-shop-hardened
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user
  namespace: sock-shop-hardened
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment
  namespace: sock-shop-hardened
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shipping
  namespace: sock-shop-hardened
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: queue-master
  namespace: sock-shop-hardened
